name: Laura Mackay Photography
description: Photography by Laura Mackay
url: http://www.LauraMackayPhotography.com

photosetHome: /
thumbPath: /photos/thumbs
largePath: /photos/large
exclude: [photos/full]

pygments: true
markdown: rdiscount
timezone: Europe/London
permalink: /:year/:month/:day/:title/
relative_permalinks: false
paginate: 5
